### ISSUE TITLE
2024 Governing Board Elections

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/community#1130]
Regular Election (until Feb 2025)

| Full Name         |  Company   | GitHub                                        | Slack                                                         | Elected On | Until    |
|-------------------|:----------:|-----------------------------------------------|---------------------------------------------------------------|------------|----------|
| Andrea Frittoli   |    IBM     | [afrittoli](https://github.com/afrittoli)   | [@Andrea Frittoli](https://tektoncd.slack.com/team/UJ411P2CC) | Feb 2022   | Feb 2024 |
| Billy Lynch       | Chainguard | [wlynch](https://github.com/wlynch)         | [@Billy Lynch](https://tektoncd.slack.com/team/UJ7BLGSB0) .   | Feb 2023   | Feb 2024 |

### Important Dates
- Sunday Feb 26 at midnight PST the nominations will close
- Monday Feb 6 we will start the voting process via http://civs.cs.cornell.edu/
- Friday Mar 2 we close the election

### Election Officers

@dibyom  
@vdemeester  
@chitrangpatel  

### Task List

Instructions at https://github.com/tektoncd/community/blob/main/governance.md#elections

- [ ] [Find Eligible voters](https://github.com/tektoncd/community/tree/main/election)
- [ ] Send Nominations email ([2022 example](https://groups.google.com/g/tekton-dev/c/kiKuPiCxeoU))
- [ ] Start the poll on Tues Feb 21 (Monday is US holiday)
- [ ] Ask tekton-dev for people we might have missed in list of eligible voters?
- [ ] March 1 - close elections midnight PST
- [ ] Send email notifying tekton-dev and tekton-users of results
- [ ] Update permissions and docs to reflect new governing board

**Comment by chitrangpatel** [comment]
This can now be closed! Thanks to everyone!
