### ISSUE TITLE
Have achieved and maintained an OpenSSF Best Practices Badge.

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/community#805]
The Core Infrastructure Initiative Best Practices Badge has been now renamed [OpenSFF Best Practices Badge Program](https://bestpractices.coreinfrastructure.org/en).

The badge shall be achieved by the following Tekton projects:

- [x] OpenSFF Best Practices Badge Program for Pipeline [#5400](https://github.com/tektoncd/pipeline/issues/5400)
- [x] OpenSFF Best Practices Badge Program for Triggers [#1438](https://github.com/tektoncd/triggers/issues/1438)
- [x] OpenSFF Best Practices Badge Program for CLI [#1692](https://github.com/tektoncd/cli/issues/1692)
- [x] OpenSFF Best Practices Badge Program for Dashboard [#2429](https://github.com/tektoncd/dashboard/issues/2429)
- [x] OpenSFF Best Practices Badge Program for Operator [#1032](https://github.com/tektoncd/operator/issues/1032)
- [x] OpenSFF Best Practices Badge Program for Chains [#536](https://github.com/tektoncd/chains/issues/536)

**Comment by afrittoli** [comment]
All badges are achieved
