### ISSUE TITLE
2023 Governing Board Elections

### ISSUE THREAD

**Issue by wlynch** [tektoncd/community#934]
Regular Election (until Feb 2025)

| Full Name         |  Company   | GitHub                                        | Slack                                                         | Elected On | Until    |
|-------------------|:----------:|-----------------------------------------------|---------------------------------------------------------------|------------|----------|
| Vincent Demeester |  Red Hat   | [vdemeester](https://github.com/vdemeester)   | [@vdemeester](https://tektoncd.slack.com/team/UHSQGV1L3)      | Feb 2021   | Feb 2023 |
| Christie Wilson   |   Google   | [bobcatfish](https://github.com/bobcatfish)   | [@Christie Wilson](https://tektoncd.slack.com/team/UJ6DECY78) | Feb 2021   | Feb 2023 |
| Dibyo Mukherjee   |   Google   | [dibyom](https://github.com/dibyom)           | [@Dibyo Mukherjee](https://tektoncd.slack.com/team/UJ73HM7PZ) | Feb 2021   | Feb 2023 |

Special Election (until Feb 2024)

| Full Name         |  Company   | GitHub                                        | Slack                                                         | Elected On | Until    |
|-------------------|:----------:|-----------------------------------------------|---------------------------------------------------------------|------------|----------|
| Priya Wadhwa<br>(currently filled by Billy Lynch)      | Chainguard | [priyawadhwa](https://github.com/priyawadhwa) | [@Priya Wadhwa](https://tektoncd.slack.com/team/U02T0CS9PN0)  | Feb 2022   | Feb 2024 |

### Important Dates
- Sunday Feb 19 at midnight PST the nominations will close
- Tues Feb 21 we will start the voting process via http://civs.cs.cornell.edu/
- Friday Mar 1 we close the election

### Election Officers

@afrittoli 
@bobcatfish 
@priyawadhwa 

### Task List

Instructions at https://github.com/tektoncd/community/blob/main/governance.md#elections

- [x] [Find Eligible voters](https://github.com/tektoncd/community/tree/main/election)
- [x] Send Nominations email ([2022 example](https://groups.google.com/g/tekton-dev/c/kiKuPiCxeoU))
- [x] Start the poll on Tues Feb 21 (Monday is US holiday)
- [x] Ask tekton-dev for people we might have missed in list of eligible voters?
- [x] March 1 - close elections midnight PST
- [x] Send email notifying tekton-dev and tekton-users of results
- [x] Update permissions and docs to reflect new governing board

**Comment by bobcatfish** [comment]
Good point @dibyom, I'll send out an email!

**Comment by bobcatfish** [comment]
Email sent: https://groups.google.com/g/tekton-dev/c/4BrY7VZfMWs

**Comment by afrittoli** [comment]
> Email sent: https://groups.google.com/g/tekton-dev/c/4BrY7VZfMWs

Thank you!!

**Comment by bobcatfish** [comment]
Looks like we're a bit behind on starting the actual election - I'm hoping we can kick it off tomorrow 🤞  @afrittoli @priyawadhwa
